name: commit
on:
  push:
    branches:
    - '"master"'
  workflow_dispatch:

env:
  GKE_ZONE: europe-west3
  ARTIFACT_REPO: scanner-darkly-repo
  IMAGE_NAME: scanner-darkly-server

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install dependecies
        working-directory: src
        run: npm ci
      - name: Run tests
        working-directory: src
        run: npm test
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Setup GCLOUD CLI
        uses: google-github-actions/setup-gcloud@v2
        with: 
          service_account_key: ${{ secrets.GKE_ADMIN_KEY }}
          project_id: ${{ secrets.PROJECT_ID
      - name: Deploy image to GCP repo
        run: gcloud builds submit --tag ${{ env.GKE_ZONE }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }} .
